---
network:
  server_bind_address:
  server_bind_port: 10076
  experiment_subproc_bind_port: 10077
  protocol: tcp

logging:
  logfile:
  experiment_subproc_logfile: logs/experiment.log

device:
  init_module: device_init_3w1
