---
network:
  server_bind_address:
  server_bind_port: 10076
  experiment_subproc_bind_port: 10077
  protocol: tcp

logging:
  logfile:
  experiment_subproc_logfile: logs/experiment.log

device:
  init_module: user_scripts.device_init_3w1

scan:
  plan_storage: "plans/"

files:
  dir: "data/"
  prefix: 3w1_data
  name_pattern: "{prefix}_{scan_id:03d}.nxs"
