---
network:
  server_bind_address:
  server_bind_port: 10076
  protocol: tcp

logging:
  logfile: mamba.log

scan:
  plan_storage: "plans/"

files:
  dir: "data/"
  prefix: 3w1_data
  name_pattern: "{session}_{prefix}_{scan_id:03d}.nxs"
  name_pattern_with_source: "{session}_{prefix}_{scan_id:03d}_{dev}_{source}.nxs"
