---
backend:
    lport: 5678
    init: "~/.mamba/init.py"
    saddons: ["mamba.backend.addon_core:saddon_core()",
              "lib_tomo:saddon_tomo()"]
    caddons: ["mamba.backend.addon_core:caddon_core()"]

frontend:
    guis: ["mamba.attitude.capi_frontend:main(atti_tomo):Main"]

