---
backend:
    lport: 5678
    init: "~/.mamba/init.py"
    saddons: ["mamba.backend.addon_core:saddon_core()",
              "mamba.attitude.raman_backend:saddon_raman()"]
    caddons: ["mamba.backend.addon_core:caddon_core()"]

frontend:
    guis: ["mamba.attitude.raman_frontend:main():Main"]

