---
backend:
    lport: 5678
    init: "~/.mamba/init.py"
    saddons: ["mamba.backend.addon_core:saddon_core()",
              "mamba.backend.auth_mdg:saddon_authmdg()"]
    caddons: ["mamba.backend.addon_core:caddon_core()"]

frontend:
    guis: ["mamba.gengyd.gengyd_gui:main():Main"]

auth_mdg:
    authserver: "ldap://202.122.39.69:389"
    proposalserver: "http://hepsweb.ihep.ac.cn/a/beamtime"

scan:
    plans: "~/.mamba/plans"

